#!/bin/sh
#
# Copyright (c) 2012 Citrix Systems, Inc.
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#

#
# tag:
#
# $Id:$
#
# $Log:$
#
#
#
cvs commit -m ""

FILES=`cat version-files`
CHK=`cat $FILES | md5sum | awk '{print $1}'`
TG=`grep $CHK version-md5sums | awk '{print $2}'`
if [ .$TG != . ]; then
	echo This code already tagged as Version $TG
	exit 0
fi

MAJOR=`cat version-major`
MINOR=`cat version-minor`
MICRO=$[ `cat version-micro` + 1 ]

echo $MICRO > version-micro

echo "$CHK	${MAJOR}.${MINOR}.${MICRO}" >> version-md5sums

cvs commit -m ""
cvs tag xcpmd-$MAJOR_$MINOR_$MICRO .
