#!/bin/sh
#
# tidy:
#
# Copyright (c) 2011 James McKenzie <20@madingley.org>,
# All rights reserved.
#
# $Id:$
#
# $Log:$
#
#
#

#
# Copyright (c) 2011 Citrix Systems, Inc.
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#

if [ -f Makefile ]; then
	make distclean
fi

for i in acconfig.h AUTHORS bstrap ChangeLog configure.in COPYING INSTALL mdist NEWS README tidy src/config.h.in `find . -name Makefile.am -print` `find . -name \*.[ch] -print` ; do
	if [ -f $i ]; then
		gimme $i
	fi
done

find . -name \*.[ch] -print | xargs indent -i2 -ts0 

find . -name \*~ -print| xargs /bin/rm -f 
find . -name \*.BAK -print| xargs /bin/rm -f
find . -name a.out -print| xargs /bin/rm -f
find . -name core -print| xargs /bin/rm -f

