#!/bin/bash
#
# Copyright (c) 2014 Citrix Systems, Inc.
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#

vm_path=$(ps ax | grep 'xen_vm_path' | sed -rn 's/^.*xen_vm_path:([^:]+):/\1/p' | grep '/vm')
INET_IS_V4V=1 LD_PRELOAD=@LIBDIR@/libv4v-1.0.so.0 DBUS_SYSTEM_BUS_ADDRESS=tcp:host=1.0.0.0,port=5556 xc-switcher.bin "${vm_path}"
