#!/bin/sh
#
# tidy:
#
# $Id:$
#
# $Log:$
#
#
#
if [ -f Makefile ]; then
	make distclean
fi

for i in acconfig.h AUTHORS bstrap ChangeLog configure.in COPYING INSTALL mdist NEWS README tidy src/config.h.in `find . -name Makefile.am -print` `find . -name \*.[ch] -print` ; do
	if [ -f $i ]; then
		gimme $i
	fi
done

find . -name \*.[ch] -print | xargs indent -i2 -ts0 

find . -name \*~ -print| xargs /bin/rm -f 
find . -name \*.BAK -print| xargs /bin/rm -f
find . -name a.out -print| xargs /bin/rm -f
find . -name core -print| xargs /bin/rm -f

